authors:
  jxnl:
    name: Jason Liu
    description: Creator
    avatar: https://pbs.twimg.com/profile_images/1682267111555571714/VDORoUy__400x400.jpg
  ivanleomk:
    name: Ivan Leo
    description: Contributor
    avatar: https://pbs.twimg.com/profile_images/1524186822389026816/sWRHRIkY_400x400.jpg